#development:
#  adapter: postgresql
#  encoding: unicode
#  database: asg_development
#  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: asg_production
  pool: 5
  username: root
  password: vjTx9TFnkm8pe2
development:
  adapter: sqlite3
  encoding: unicode
  database: db/asg_development.sqlite3
  pool: 5
#production:
#  adapter: sqlite3
#  encoding: unicode
#  database: db/asg_production.sqlite3
#  pool: 5
